# Generated by Django 4.2.1 on 2024-02-14 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MyEcommerceApp", "0001_squashed_0004_add_changes_and_delete_examples"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productmodel",
            name="short_description",
        ),
    ]
