# Generated by Django 4.2.1 on 2024-02-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("MyEcommerceApp", "0001_initial"),
        ("MyEcommerceApp", "0002_productmodel_color_productmodel_description_and_more"),
        ("MyEcommerceApp", "0003_alter_productmodel_color_and_more"),
        ("MyEcommerceApp", "0004_productmodel_short_description"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("price", models.FloatField()),
                ("color", models.CharField(default="VALOR POR DEFAULT", max_length=50)),
                ("description", models.TextField(null=True)),
                (
                    "product_dimensions",
                    models.CharField(default="VALOR POR DEFAULT", max_length=100),
                ),
                (
                    "seller",
                    models.CharField(default="VALOR POR DEFAULT", max_length=100),
                ),
                ("short_description", models.TextField(null=True)),
            ],
        ),
    ]
