# Generated by Django 4.2.1 on 2024-02-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyEcommerceApp", "0005_remove_productmodel_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="state",
            field=models.CharField(
                choices=[("BR", "BORRADOR"), ("PU", "PUBLICADO"), ("PR", "PRIVADO")],
                default="BR",
                max_length=2,
            ),
        ),
    ]
