# Generated by Django 4.2.1 on 2024-02-15 00:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("MyEcommerceApp", "0007_alter_productmodel_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmodel",
            options={"ordering": ["-updated", "-timestamp"]},
        ),
        migrations.AddField(
            model_name="productmodel",
            name="publish_timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productmodel",
            name="updated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
