# Generated by Django 4.2.1 on 2024-02-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyEcommerceApp", "0008_alter_productmodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
